// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GenrateAIContext
{
    internal sealed partial class Vsix
    {
        public const string Id = "GenrateAIContext.57db8ea2-bbfb-4c85-a80b-e4ba6ee4eca2";
        public const string Name = "GenrateAIContext";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
